[package]
name = "xraytui"
description = "xraytui terminal user interface and command line client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "xraytui"
path = "src/main.rs"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
xraytui-cli = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
